# Flyway configuration for containerised migrations
flyway.locations=filesystem:/flyway/sql
flyway.baselineOnMigrate=true
flyway.baselineVersion=1
flyway.baselineDescription=<< Flyway Baseline >>
flyway.validateOnMigrate=true
flyway.outOfOrder=true
flyway.cleanDisabled=true
flyway.placeholderReplacement=false
flyway.defaultSchema=public
